/**
 *
 * $Id$
 */
package Engine.validation;

import Engine.Task;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Engine.ResultTask}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResultTaskValidator {
	boolean validate();

	boolean validateResult(int value);
	boolean validateTask(EList<Task> value);

	boolean validateResultName(String value);

	boolean validateTask(Task value);
}
