/**
 *
 * $Id$
 */
package petrinet.validation;

import petrinet.Node;
import petrinet.PetriNet;

/**
 * A sample validator interface for {@link petrinet.Arc}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArcValidator {
	boolean validate();

	boolean validateNet(PetriNet value);
	boolean validateSource(Node value);
	boolean validateTarget(Node value);
}
