/**
 *
 * $Id$
 */
package petrinet.validation;

import org.eclipse.emf.common.util.EList;

import petrinet.Arc;
import petrinet.Node;

/**
 * A sample validator interface for {@link petrinet.PetriNet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PetriNetValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateNodes(EList<Node> value);
	boolean validateArcs(EList<Arc> value);
}
